name: oghunt

services:
  db:
    image: bitnami/postgresql
    container_name: oghunt-db
    restart: always
    environment:
      POSTGRESQL_USERNAME: dev
      POSTGRESQL_PASSWORD: dev
      POSTGRESQL_DATABASE: oghunt
    volumes:
      - oghunt-data:/bitnami/postgres/data
    ports:
      - 5432:5432
volumes:
  oghunt-data:
    driver: local
