name: oghunt

services:
  db:
    # rolling tags fucked us, so downgrading for now
    # https://github.com/bitnami/containers/issues/74788
    image: bitnami/postgresql:13
    container_name: oghunt-db
    restart: always
    environment:
      POSTGRESQL_USERNAME: dev
      POSTGRESQL_PASSWORD: dev
      POSTGRESQL_DATABASE: oghunt
      POSTGRESQL_TIMEZONE: America/Chicago
    # create a volume for the docker container_name
    volumes:
      - oghunt-data:/bitnami/postgres/data
    ports:
      - 5432:5432
volumes:
  oghunt-data:
    driver: local
